// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBopMz33MtGtUzSYaucxL8mNtqARn3hJIE',
    appId: '1:701128808505:web:d24df8e9904090cc5495e8',
    messagingSenderId: '701128808505',
    projectId: 'chatter-ef53b',
    authDomain: 'chatter-ef53b.firebaseapp.com',
    storageBucket: 'chatter-ef53b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW2uMSQzGmHnsaS-LK3fJEhF4UyG1772o',
    appId: '1:701128808505:android:1ec0eadcc874e8d75495e8',
    messagingSenderId: '701128808505',
    projectId: 'chatter-ef53b',
    storageBucket: 'chatter-ef53b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlEhv-FAwwMVbnwrEMy-a_oSLLSzKc3TY',
    appId: '1:701128808505:ios:ee6dcfb289a084885495e8',
    messagingSenderId: '701128808505',
    projectId: 'chatter-ef53b',
    storageBucket: 'chatter-ef53b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlEhv-FAwwMVbnwrEMy-a_oSLLSzKc3TY',
    appId: '1:701128808505:ios:ee6dcfb289a084885495e8',
    messagingSenderId: '701128808505',
    projectId: 'chatter-ef53b',
    storageBucket: 'chatter-ef53b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBopMz33MtGtUzSYaucxL8mNtqARn3hJIE',
    appId: '1:701128808505:web:89e560ecb8f9b1bf5495e8',
    messagingSenderId: '701128808505',
    projectId: 'chatter-ef53b',
    authDomain: 'chatter-ef53b.firebaseapp.com',
    storageBucket: 'chatter-ef53b.appspot.com',
  );
}
